### ISSUE TITLE
_.template('foo.pug')と拡張子込みで指定できるようにする

### ISSUE THREAD

**Issue by aokiken** [aokiken/gulp-pug-template-underscore#4]
現在は_.template('foo')という指定がfoo.pugを示しているとなっているが、
いまいちわかりにくい気もするので、_.template('foo.pug')と指定できるようoptionで追加出来るようにする。

**Comment by aKenAoki** [comment]
/_.template\('.*?'\)/ではなく/_.template\('.*?.pug'\)/と指定するほうがベター?
